### PR TITLE
update Go from 1.12 to 1.16; update orbs and cimgs

### LINKED ISSUE #13: Update to cimg/go image and go 1.16.x

### PR DESCRIPTION
**Pull request by robbkidd**
Closes #13

### CODE REVIEW

**Comment by robbkidd** [comment]
These changes will be happier when #10 merges to switch to Go modules.

**Comment by vreynolds** [comment]
@robbkidd can you add a "skip buildevents" for forks, like we did here: https://github.com/honeycombio/opentelemetry-exporter-python/blob/889e8977d0cd577bede12c513f76febdc959708f/.circleci/config.yml

```
      - watch:
          context: Honeycomb Secrets for Public Repos
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /pull\/.*/
          requires:
            - setup_trace
```

**Comment by robbkidd** [comment]
> can you add a "skip buildevents" for forks

Absolutely!

**Review by vreynolds — APPROVED** [review]
Improvements! 🏗️

**Pull request merged**
